### ISSUE TITLE
Music doesn't start again after a notification

### ISSUE THREAD

**Issue by mcsac** [MissingCore/Music#30]
### What device did this occur on?

Nothing Phone 2a

### What version of Android is your device running?

Android 14

### App Version

v1.0.0-rc.9

### Summary

It's not really a bug, when using headphones after an interruption due to a notification the audio doesn't restart automatically

### Screenshot / Video

N/A

**Comment by cyanChill** [comment]
I believe currently, the libraries/package we use for handling audio doesn't support this behavior.

Currently, we're synchronizing 2 different libraries - one that handles audio and another that handles the media notification. We have logic that you can find [here](https://github.com/MissingCore/Music/blob/main/src/features/playback/api/actions.ts#L110) in which we pause the audio whenever we get an interruption.
- The code is in an event listener triggered by the library that plays the audio. I don't believe that after it outputs values that indicates an interruption, it will output values again signaling an unpause.

I would like to fix it so it does what you're expecting, but currently there's other things of more importance that needs to be worked on. I'm potentially planning to rewrite the playback logic some time in the future when things are more stable, so this might get fix then.

**Comment by mcsac** [comment]
Thank you for what you are doing, I will wait patiently. The application itself is very nice though
