### ISSUE TITLE
Couldn't Detect Music!

### ISSUE THREAD

**Issue by Exotic-Lambo** [MissingCore/Music#46]
Device: Redmi Note 10 Pro
OS: Android 14 QPR3
Version: v1.0.0-rc10

Description: I have about 2000 AAC Tracks in my library. The app shows the folders but no music in any section and insights doesn't show any bugs either.

All my music is detected in every other music app used to music for reference.

![Screenshot_20240726-200646.png](https://github.com/user-attachments/assets/403d6646-5b06-4448-a7a3-3138e92a0337)

Screenshots![Screenshot_20240726-200025.png](https://github.com/user-attachments/assets/9fa9a7ed-9bf8-446b-a19d-9663793c00e8)

![Screenshot_20240726-200657.png](https://github.com/user-attachments/assets/597bd14d-271c-4334-8eaa-44045137ac3c)

![Screenshot_20240726-200122.png](https://github.com/user-attachments/assets/782f23b8-47c0-4ae0-8355-89c5bc082aff)

**Comment by cyanChill** [comment]
@Exotic-Lambo `v1.0.0-rc.11` has been released which changes what we use to get the metadata of the tracks (now using an Android API vs some manual logic).

We've also added an allowlist/blocklist feature in case your Music isn't located in the default location of the `Music` directory on your device.
