### ISSUE TITLE
I don't see music anymore

### ISSUE THREAD

**Issue by PSFaceLLC** [MissingCore/Music#52]
### What device did this occur on?

Nothing Phone 2a

### What version of Android is your device running?

14

### App Version

version 1.0.0-rc.10

### Summary

After updating to the latest version the music no longer appears in the app... To fix it just downgrade to the previous version but I would still like it to be fixed in the next release because I would like to be able to update it to listen to music, not to see a blank screen, thanks and sorry for the inconvenience.

### Screenshot / Video

![Screenshot_20240803-141404](https://github.com/user-attachments/assets/ded1ce0e-2efc-4e3a-ae7a-d1ef0651ef52)

**Comment by cyanChill** [comment]
Hi, with the latest update, we noted that we'll start enforcing that music discovered by the app has to be in the `Music` directory. It's seem like that in this case, your music probably isn't in that folder.

With people not really putting their music in the `Music` directory most of the time; I've decided to speed up adding a whitelist/blacklist feature, which should be added in the next update.

I was thinking of having the feature default to our current behavior (look for tracks in the `Music` directory) and have the user remove the defaults if their music isn't located there. This is probably a more balanced option as if people preferred to have the app search for music only in this directory, then there's no changes necessary. If people don't have music in the `Music` directory, the app will load faster (albeit, with no tracks found), and they can just simply change this setting.

**Comment by PSFaceLLC** [comment]
Thank you very much for the reply and I apologize again, I can't wait for the new version to come out if that will allow me to see music from folders other than the Music folder, thanks again.

**Comment by cyanChill** [comment]
@PSFaceLLC `v1.0.0-rc.11` has been released which should fix things as we've added an allowlist/blocklist system. It'll default to the behavior seen in `v1.0.0-rc.10` (looks only at the `Music` directory on each storage device), but you can change that (ie: remove the defaults and allow the app to search from anywhere).

You can refer to the [`Where Are Tracks Found?`](https://github.com/MissingCore/Music/blob/main/docs/where-are-tracks-found.md) docs for more info.
