### ISSUE TITLE
The app doesnt recognise m4a music files

### ISSUE THREAD

**Issue by DebadityaMalakar** [MissingCore/Music#53]
Also the app doesnt seem to have the option to replay a specific song instead of the entire playlist

**Comment by DebadityaMalakar** [comment]
This was tested on my oneplus nord 4 devicd

**Comment by DebadityaMalakar** [comment]
This was tested on my oneplus nord 4 devicd

**Comment by cyanChill** [comment]
To answer your questions:

- Currently, we only support `.mp3` & `.flac` files - other file support will come in the next release.
- For replaying a specific song, if you mean loop a song, the only method currently is to create a playlist with just that track. If you mean you want to play that track again after it finishes, you can use the queue feature and add it to the queue.

**Comment by DebadityaMalakar** [comment]
So is the loop current song going to be added soon or will i have to wait some time?

**Comment by cyanChill** [comment]
A dedicated feature for looping a single song probably won't happen as I don't really see a need for it. If there's more people that want this feature, I'll think about it.

As mentioned above, there are some alternatives such as:
- Creating a playlist with that single track and play the playlist in repeat.
- If you want to play the track back to back temporarily, you can use the queue feature and add that track to the queue x times.

**Comment by cyanChill** [comment]
@DebadityaMalakar `v1.0.0-rc.11` has been released and should now detect `.m4a` files as we now use an Android API to get the metadata of the track.

**Comment by cyanChill** [comment]
In regards to the repeat a single song feature, if you're using the APK version of the app, you can try it out in [`v2.0.0-rc.1`](https://github.com/MissingCore/Music/releases/tag/v2.0.0-rc.1).
