### ISSUE TITLE
Tracks won't show up

### ISSUE THREAD

**Issue by Thegitallay** [MissingCore/Music#55]

**Comment by cyanChill** [comment]
Duplicate of #55; tldr, should be fixed in next update.

**Comment by cyanChill** [comment]
@Thegitallay `v1.0.0-rc.11` has been released which adds an allowlist/blocklist system along with changing what we use to get track metadata (incase the files you have were unsupported).

If your music isn't located in the `Music` directory of your device, then you should change what's in the allowlist/blocklist (we currently default to only looking in the `Music` directory in each storage device).

You can refer to the [`Where Are Tracks Found?`](https://github.com/MissingCore/Music/blob/main/docs/where-are-tracks-found.md) docs for more info.
