### ISSUE TITLE
Modal doesn't collapse with "back" gesture/action

### ISSUE THREAD

**Issue by Bushrangers** [MissingCore/Music#74]
### What device did this occur on?

np1

### What version of Android is your device running?

14

### App Version

rc.12

### Summary

Music file format suffixes are often used to distinguish between different audio encoding and compression techniques. Here are some common music file formats and their suffixes:

1. MP3 - `.mp3`
2. WAV - `.wav`
3. AAC - `.aac`
4. FLAC - `.flac`
5. ALAC (Apple Lossless Audio Codec) - `.alac`
6. OGG - `.ogg`
7. WMA (Windows Media Audio) - `.wma`
8. AIFF (Audio Interchange File Format) - `.aiff`
9. M4A (MPEG-4 Audio) - `.m4a`
10. MP2 - `.mp2`
11. APE (Monkey's Audio) - `.ape`
12. DSD (Direct Stream Digital) - '.dff 'or'.dfs'

The above music formats cannot be detected in the playlist, for example, some mp3 and ape formats cannot be detected in the playlist, but other apps can detect them. The interface returns the menu bar, see the following figure for details

### Screenshot / Video

![20240814145559](https://github.com/user-attachments/assets/8a213140-b050-42c1-9000-bc90a1f8ec7c)
![20240814145609](https://github.com/user-attachments/assets/e2e70e8c-30fb-4912-a911-d873c4ce9547)

**Comment by Bushrangers** [comment]
What the screenshot wants to express is that after clicking the three dots menu in the upper right corner of the playback interface, the return gesture menu will not be removed when you click other areas in the playlist. I personally think that the interface should be removed when the return gesture is used in the playback interface, of course, these are just some of my opinions

**Comment by cyanChill** [comment]
The original explanation in the issue was bit confusing since it mainly talks about music file formats when the issue is mainly a UI (User Interface) issue with the modal not collapsing with the back gesture/action.

**Comment by cyanChill** [comment]
The back gesture/action should now close the modal before it attempts to navigates back a screen. This should be available in the `v1.0.0` release.

Also, the modal can be closed by clicking the transparent area around it.

**Comment by Bushrangers** [comment]
I think there is no problem with the title, but there are two questions raised. You have already explained that the music format detection is not complete. I just want to answer that you do not understand the meaning of the screenshot

**Comment by Bushrangers** [comment]
I think there is no problem with the title, but there are two questions raised. You have already explained that the music format detection is not complete. I just want to answer that you do not understand the meaning of the screenshot. Gesture return problem: I just think that if the return operation has been triggered, I should fold the menu, of course, click on other areas can also fold but feel unnecessary
